### PR TITLE
Allow to pass free queries as `select * from table limit 100` in moran

### PR DESCRIPTION
**Pull request by rochoa**
cc @ohasselblad 

This closes #7

### CODE REVIEW

**Comment by ohasselblad** [comment]
Great idea :) I made some updates and updated the tests. Would it be reasonable to expect either `table_name` or `query`? Right now it's expecting a full query like `SELECT cartodb_id, interesting_column, the_geom FROM table_name`. It would fail if any of those are not present in the query.

**Comment by rochoa** [comment]
It should work with both: `select * from table_name` or just `table_name`.

**Comment by rochoa** [comment]
Hmmm. Not so sure. I will double check but I think it's not gonna work for `table_name`.

**Comment by ohasselblad** [comment]
Yeah, it won't work for `table_name`. I tried with `(table_name)` and it failed, so I moved to `(SELECT * FROM table_name)`. 

I could put some more logic in there to check if it's a query or a table name.

**Comment by rochoa** [comment]
Probably the best option is to just allow SQL queries. Another option would be to have two functions with different signature:
 1. `cdb_moran_local_rate(query text,,...)`
 1. `cdb_moran_local_rate(t regclass,...)`

**Comment by ohasselblad** [comment]
handled in #12

**Pull request closed without merging**
