### PR TITLE
Moran query ordering fix

### PR DESCRIPTION
**Pull request by ohasselblad**
There's a bug that flips the order of the numerator in denominator for calculating using Moran Local Rate because previously the code sorted the keys alphabetically.

### CODE REVIEW

**Comment by ohasselblad** [comment]
@iriberri, could you take a look at this, please?? :) There was a bug where the numerator and denominator were being swapped, leading to clusters being assigned the opposite of the correct answer!

**Comment by iriberri** [comment]
HI @ohasselblad, it looks good to me from my point of view, but perhaps it's worth it that someone else in Research takes a quick look too? I'm not that familiar with Moran so I'm not sure if I would be missing something here.

**Comment by ohasselblad** [comment]
thanks @iriberri!

@talos, could you give this a look please?

**Comment by talos** [comment]
This looks good on the surface to me, but we'd need to talk about it together for me to really grok it.

**Comment by ohasselblad** [comment]
@CartoDB/dataservices ready to be merged in!

**Pull request merged**
