### PR TITLE
Adds getis analysis

### PR DESCRIPTION
**Pull request by ohasselblad**
- [x] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [x] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [x] Docs for public-facing functions are written
- [x] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore
- [x] Video explaining the analysis and showing examples 
- [x] Analysis Documentation written [template](https://docs.google.com/a/cartodb.com/document/d/1X2KOtaiEBKWNMp8UjwcLB-kE9aIOw09aOjX3oaCjeME/edit?usp=sharing)
- [ ] Smoke test written

### CODE REVIEW

**Comment by ohasselblad** [comment]
@stuartlynn @talos could you give this code a look, please?

**Comment by ohasselblad** [comment]
@AbelVM, could you do a CR of this, please? :)

**Comment by AbelVM** [comment]
I'd love to, but my python skills are not up to this level :(

**Comment by ohasselblad** [comment]
Ok, thanks @AbelVM, I'll have one for you in PL/pgSQL soon ;)

@mehak-sachdeva, could you take a look at this please?

**Comment by AbelVM** [comment]
Sure!

**Comment by stuartlynn** [comment]
This looks good to me @ohasselblad. I think its good to be merged

**Comment by ohasselblad** [comment]
@CartoDB/dataservices this is ready to be merged

**Pull request merged**
