### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by stuartlynn**
- [ ] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [ ] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [ ] Docs for public-facing functions are written
- [ ] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore `_`.
- [ ] If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)

### CODE REVIEW

**Comment by stuartlynn** [comment]
We want to make sure we are capturing the correct documentation for each analysis so changing this to reflect that

**Comment by iriberri** [comment]
Why did  ` If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)` get deleted?

**Comment by stuartlynn** [comment]
Hey @iriberri we figured out (for the most part) how to avoid passing query strings to the functions and instead do some clever passing of arrays around so that seemed less relevant now. We can add it back in if you think its appropriate.

**Comment by iriberri** [comment]
Thanks for the answer @stuartlynn! I don't really mind, I was just checking just in case it was deleted by accident :)

Awesome! :+1:

**Comment by ohasselblad** [comment]
@CartoDB/dataservices this is ready to be merged

**Comment by ohasselblad** [comment]
`develop` needs to be merged into here to update the Travis file

**Pull request merged**
