### PR TITLE
Add densify / tinmaps functions [14] [15]

### PR DESCRIPTION
**Pull request by AbelVM**
- [x] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [x] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [x] Docs for public-facing functions are written
- [x] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore `_`.
- [ ] If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)

### CODE REVIEW

**Comment by AbelVM** [comment]
Looks like the tests are failing due to different versions of PostgreSQL / PostGIS in testing machine vs travis. so the results differ in epsilons

cc @rafatower

**Comment by rafatower** [comment]
I'd say the files differ in blank spaces https://travis-ci.org/CartoDB/crankshaft/builds/151282201#L1035

I'll take a further look tomorrow. Anyway I want to prepare a release with the gravity stuff asap, testing all the process scripts & improvements

**Comment by AbelVM** [comment]
Okidoki, I'm debugging it meanwhile

**Comment by AbelVM** [comment]
Demos
* CDB_Densify: https://team.carto.com/u/abel/builder/08655476-16b5-11e6-9826-0e3ff518bd15/embed
* CDB_TINmap: https://team.carto.com/u/abel/builder/f35f0a90-1781-11e6-a32d-0ecd1babdde5/embed

**Comment by AbelVM** [comment]
selection_004

**Comment by iriberri** [comment]
What about "All declared geometries are geometry(Geometry, 4326) for general geoms, or geometry(Point, 4326)" here? I'm missing the checkboxes :)

**Comment by AbelVM** [comment]
Checked. :grin: It wasn't because these functions work the same regardless of the projection used

**Pull request merged**
