### PR TITLE
incrementing version

### PR DESCRIPTION
**Pull request by ohasselblad**
@jgoizueta we're ready for a version bump

### CODE REVIEW

**Comment by rochoa** [comment]
This is missing some important pieces:
 - Release file for 0.0.5 version.
 - Upgrade and downgrade paths for Postgresql.
 - Release directory for 0.0.5 version.

Examples for:
 - 0.0.3 version: https://github.com/CartoDB/crankshaft/commit/8b5e9102345fc2a7218961ef26c033715a441d6b
 - 0.0.4 version: https://github.com/CartoDB/crankshaft/commit/01fc2c1dd1087e58679cc2728ee88a0df5702ea6

**Comment by ohasselblad** [comment]
Yep, those pieces are handled by the release manager. This PR is asking for an increment bump, and the release manager handles the merge into master from here. This is how we handled the handover form research to product.

**Comment by ohasselblad** [comment]
@jgoizueta, is there anything else you need from me on this?

**Comment by rafatower** [comment]
I'm afraid the release doc was misinterpreted:

https://github.com/CartoDB/crankshaft/blob/develop/RELEASE.md
> Having checked PR to be released it shall be merged back into the master branch to prepare the new release.

The intent of having two distinct branches `master` and `develop` is allowing for the preparation of releases (the versioning stuff in `master`) while at the same time allow for concurrent development in `develop`.

I know the process is not the best one ever and the docs are so-so. This PR just hints the need of improvements.

Meanwhile I'm closing this PR and taking care of the release.

**Pull request closed without merging**
