### PR TITLE
[Add interpolation] Tests for the three methods [08]

### PR DESCRIPTION
**Pull request by AbelVM**
- [ ] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [ ] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [ ] Docs for public-facing functions are written
- [ ] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore `_`.
- [ ] If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)

### CODE REVIEW

**Comment by rafatower** [comment]
please do not assign to me until the tests are passing

**Comment by AbelVM** [comment]
Wilco! I doubted if assigning or just mentioning, sorry!

**Comment by rafatower** [comment]
hahaha! also you should find a suitable reviewer for your PR's and I don't feel like the right person for many "deep spatial" stuff :)

**Comment by AbelVM** [comment]
Maybe, there should be 2 reviewers per PR:
* Code reviewer
* Functional reviewer (geospatial and so on)

**Comment by AbelVM** [comment]
Green light

**Pull request merged**
