### PR TITLE
Creating requirements.txt file for python

### PR DESCRIPTION
**Pull request by jvillarf**
Related ticket: https://github.com/CartoDB/cartodb-platform/issues/2547

From those lines (https://github.com/CartoDB/crankshaft/blob/develop/src/py/crankshaft/setup.py#L36-L38), i guess none of them is required, as we are not in a dev, nor test environment.

cc/ @rafatower @ethervoid

### CODE REVIEW

**Comment by jvillarf** [comment]
I've just realized that it'd be smart to add a **requirements.txt** file per **extension version**. For instance, here: https://github.com/CartoDB/crankshaft/tree/develop/release/python/0.4.2/crankshaft

As we are deploying the extension for a given **RELEASE_VERSION**, it does make sense to include the requirements.txt file within that version folder, just the same way we are doing with setup.py, right?

**Comment by ethervoid** [comment]
That is going to be done by the Makefile https://github.com/CartoDB/crankshaft/blob/develop/src/py/Makefile#L13

**Comment by jvillarf** [comment]
Yep, but this won't be executed until we release the next version, so do you see any inconvenient on "manually" copying it there, just for 0.4.2 release? Thanks.

**Comment by ethervoid** [comment]
Nope, shouldn't be a problem at all :)

**Pull request merged**
