### PR TITLE
cdb_union_adjacent

### PR DESCRIPTION
**Pull request by stuartlynn**
Adding a function to union together touching polygons in to continuous regions. Not sure if they test are set up properly because I am having trouble getting crankshaft working with my homebrew version of postgresql, seems to be defaulting to my systems install.

### CODE REVIEW

**Comment by stuartlynn** [comment]
@jgoizueta let me know if you have any feedback esp about the testing

**Comment by jgoizueta** [comment]
@stuartlynn have you considered using ST_ClusterIntersecting to implement this?

**Comment by stuartlynn** [comment]
Ah I was trying to find a function like that for ages but obviously didn't hit the magic combination of google search phrases so gave up and wrote this. Will take a look and see if we can give it a bit of a clearer name and make it a bit easier to use

**Comment by pramsey** [comment]
Yes, I think you should really look at `ST_ClusterIntersecting` (and in PostGIS 2.3, ST_ClusterDBSCAN) for this. The iteration in this aggregate will be painful as the whole table gradually has to be stuffed through each iteration in the transfnc, serialized and de-seralized along the way. Clustering is still memory bound, but it's a one-time cost to pull everything into memory, find the clusters, then spit out the answer.

**Comment by ohasselblad** [comment]
moved to #14 after reorganization of repo

**Pull request closed without merging**
