### PR TITLE
[FIX] Voronoi spurious segments [09]

### PR DESCRIPTION
**Pull request by AbelVM**
* Removes the unwanted segments
* Tweak the buffering code to be more strict

- [x] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [x] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [x] Docs for public-facing functions are written
- [x] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore `_`.
- [x] If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)

### CODE REVIEW

**Comment by iriberri** [comment]
A silly detail: wouldn't the doc have to be updated to set the SRID of the geoms as in the test?

**Comment by AbelVM** [comment]
All geoms are 4326 by default in Crankshaft, afaik

**Comment by iriberri** [comment]
Vamos!

**Comment by AbelVM** [comment]
Oleeeeeeee :dancer:

**Pull request merged**
