### PR TITLE
updating and adding clustering functions

### PR DESCRIPTION
**Pull request by ohasselblad**
This updates and adds to the clustering functionality already in this extension.

@jgoizueta, should I bump the version or are we early enough still that we'll stay with 0.0.1? I do change the signatures of most of the functions in `clustering`.

### CODE REVIEW

**Comment by jgoizueta** [comment]
I've tagged the current 0.0.1, which is what we are using for some tests with DO.

So we'll bump the version for your changes. Remember we should not change function signatures, but since we're still at 0.* we can actually change anything.

I'll consider tomorrow how we proceed with this changes and which version number we use.

**Comment by ohasselblad** [comment]
Thanks -- please let me know if there's anything I can change on my end.

The output of the function no longer has 'not significant'.. it simply gives 'HH', 'LL', 'HL', and 'LH'. Should I alter the [`moran.json`](https://github.com/CartoDB/crankshaft/blob/master/python/crankshaft/test/fixtures/moran.json) file to reflect this change? Sorry for the changes.

**Comment by ohasselblad** [comment]
I need to fix some tests, so please hold off merging this

**Comment by jgoizueta** [comment]
Sin 0.0.1 hasn't been publicly released, we'll change function signatures as needed for next version 0.0.2

We'll define how we'll handle versioning before the first public release. (some options to be considered are versioning the schema, using function name suffixes, ...)

@ohasselblad you're right changing moran.json, that's the expected results for the test data in neighbors.json, feel free to replace that for more meaningful test data.

**Comment by ohasselblad** [comment]
@jgoizueta, all is good on my side (tests pass). ready to update this when you decide on the versioning structure :)

**Comment by ohasselblad** [comment]
closing, moved to https://github.com/CartoDB/crankshaft/pull/19 after repo restructure

**Pull request closed without merging**
