### PR TITLE
Add Pole of Inaccessibility [13]

### PR DESCRIPTION
**Pull request by AbelVM**
- [x] All declared geometries are `geometry(Geometry, 4326)` for general geoms, or `geometry(Point, 4326)`
- [x] Existing functions in crankshaft python library called from the extension are kept at least from version N to version N+1 (to avoid breakage during upgrades).
- [x] Docs for public-facing functions are written
- [x] New functions follow the naming conventions: `CDB_NameOfFunction`. Where internal functions begin with an underscore `_`.
- [x] If appropriate, new functions accepts an arbitrary query as an input (see [Crankshaft Issue #6](https://github.com/CartoDB/crankshaft/issues/6) for more information)

### CODE REVIEW

**Comment by AbelVM** [comment]
There's a lot of room for improvement, but this is a pretty good start.

**Comment by AbelVM** [comment]
performance x20 !!

Las Palmas de Gran Canaria (multigeometry, 12 polygons, with a total of 13281 points) --> 210ms

**Comment by AbelVM** [comment]
Travis can't find [CDB_RectangleGrid](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_RectangleGrid.sql) and fails... :cry:

**Comment by iriberri** [comment]
Does this one work in 3857?

**Comment by AbelVM** [comment]
All the inputs/outputs must be 4326 in Crankshaft

**Comment by iriberri** [comment]
So why the example in the doc is inputting a 3857 geometry? I'm mostly curious about it.

**Pull request merged**
